- packetbeat/protos/http/http_parser.go
- packetbeat/protos/http/http_parser_test.go
> chore(parser): export http parser refs SERVICE_OBSERVE-1307

- libbeat/metric/system/process/process_linux_common.go
Some process have as a cmdline that like "XXX\0\0\0". It will be convert into "XXX   ". This pr will fix it. After merge, the cmdline will be converted to "XXX".
-
> chore(): remove extra spaces from cmdline

- metricbeat/helper/easyops/cou_metric_builder.go
- metricbeat/helper/easyops/div_metric_builder.go
- metricbeat/helper/easyops/sub_metric_builder.go
- metricbeat/helper/easyops/sum_metric_builder.go
- metricbeat/helper/easyops/types.go
- metricbeat/helper/easyops/util.go
- metricbeat/helper/prometheus/prometheus.go
- metricbeat/module/kubernetes/container/container.go
- metricbeat/module/kubernetes/container/data.go
- metricbeat/module/kubernetes/node/data.go
- metricbeat/module/kubernetes/node/node.go
- metricbeat/module/kubernetes/state_container/state_container.go
- metricbeat/module/kubernetes/state_node/state_node.go
- metricbeat/module/kubernetes/state_pod/state_pod.go
- metricbeat/module/kubernetes/volume/data.go
- metricbeat/module/kubernetes/volume/volume.go
> feat(metricbeat): add aggregate metrics

- metricbeat/module/kubernetes/container/container.go
- metricbeat/module/kubernetes/node/node.go
> feat(): add aggregate metrics refs MONITOR-4326

- metricbeat/module/kubernetes/state_node/state_node.go
> feat(): node.normal.status refs MONITOR-4326

- metricbeat/module/kubernetes/state_node/state_node.go
> fix(): remove namespace dim refs MONITOR-4326

- metricbeat/helper/easyops/cou_metric_builder.go
- metricbeat/helper/easyops/div_metric_builder.go
- metricbeat/helper/easyops/sub_metric_builder.go
- metricbeat/helper/easyops/sum_metric_builder.go
- metricbeat/helper/easyops/types.go
- metricbeat/module/kubernetes/state_pod/state_pod.go
> feat(): default values refs MONITOR-4326

- metricbeat/module/kubernetes/state_pod/state_pod.go
> fix(): fix field name refs MONITOR-4326

- metricbeat/helper/easyops/sub_metric_builder.go
> fix(): fix sub metric buidler refs MONITOR-4326

- metricbeat/module/kubernetes/node/node.go
> fix(): fix aggregate type refs MONITOR-4326

- metricbeat/module/kubernetes/container/container.go
> fix(): fix pod.memory.usage.pct refs MONITOR-4326

- go.mod
- go.sum
> chore(): gosigar remove file line read limit

- go.mod
- go.sum
- metricbeat/module/system/diskio/diskio.go
> chore(): add iostat metric for system module

- metricbeat/module/docker/diskio/data.go
- metricbeat/module/docker/network/data.go
> chore(): add docker deprecated field

- metricbeat/module/mongodb/collstats/collstats.go
- metricbeat/module/mongodb/status/status.go
> feat(mongodb): add mongodb custom collector metrics

- metricbeat/module/mongodb/replstatus/data.go
- metricbeat/module/mongodb/status/status.go
> feat(mongodb): add mongodb.replstatus.optimes.delay metric

- metricbeat/module/mongodb/replstatus/data.go
- metricbeat/module/mongodb/replstatus/status.go
> fix(): modify metric calculation method

- go.mod
- go.sum
- metricbeat/module/system/filesystem/filesystem.go
- metricbeat/module/system/fsstat/fsstat.go
> chore(): support collect type

- x-pack/metricbeat/module/mssql/database/database.go
> fix(): MSSQL database metric set

- go.mod
- go.sum
统一 easyops sampler 获取 cmdline 逻辑
> chore(): 统一 easyops sampler 获取 cmdline 逻辑

- metricbeat/module/kubernetes/util/pod_prefix_extractor.go
> feat(pod-prefix): extract Kubernetes Pod prefix

- metricbeat/module/redis/_meta/config.reference.yml
- metricbeat/module/redis/_meta/config.yml
- metricbeat/module/redis/config.go
- metricbeat/module/redis/info/info_integration_test.go
- metricbeat/module/redis/key/key_integration_test.go
- metricbeat/module/redis/keyspace/keyspace_integration_test.go
- metricbeat/module/redis/metricset.go
- metricbeat/module/redis/metricset_integration_test.go
- metricbeat/module/redis/metricset_test.go
- metricbeat/module/redis/redis.go
- metricbeat/module/redis/redis_integration_test.go
> chore(): support redis username

- metricbeat/module/kubernetes/container/container.go
- metricbeat/module/kubernetes/container/data.go
- metricbeat/module/kubernetes/pod/data.go
- metricbeat/module/kubernetes/pod/pod.go
- metricbeat/module/kubernetes/volume/data.go
- metricbeat/module/kubernetes/volume/volume.go
> fix(kubernetes): extract workload name

- metricbeat/helper/prometheus/parser.go
- metricbeat/helper/prometheus/prometheus.go
> chore(kubernetes): optimize parsing KSM metrics

- metricbeat/module/kafka/consumergroup/query.go
> do not report -1 of offset(wrong data)

- metricbeat/module/redis/keyspace/data.go
> fix(): fix redis7 keyspace info
